# Header
menu:
  Home: "#body"
  About: "#about"
  Product: "#product"
  Work: "#work"
  Contact: "#contact"

first_name: KeRui
last_name:
job_title:
- KeRui Instruments Supports On Demand Customization, Good Equipment Originates from Higher Pursuit
- Looking forward to your cooperation


social:
  icon-social-github: https://github.com/rayspock
  icon-social-linkedin: https://github.com/rayspock
  icon-social-facebook: https://github.com/rayspock
  icon-social-twitter: https://github.com/rayspock
  icon-social-instagram: https://github.com/rayspock
  
# Miscellaneous
favicon: /favicon.png
header_logo: img/logo.png
header_logo_dark: img/logo.png
footer_logo: img/logo.png
slider: img/1920x1080/01.jpg
open_graph: 

# About
about:
  title: "Intro"
  subtitle: "What I am all about."
  description: "GongYi KeRui Instrument co., Ltd. is a scientific and technological enterprise integrating research, development production and sales of laboratory equipment, teaching testing equipment and scientific research and pharmaceutical facilities.after many years and, state key laboratory of colleges and universities, new drug development unit cooperation, research and development production of a variety of experimental instruments and equipment .
                Our company will rely on strong technology and work with friends from all walks of life, continue to pursue the professionalism of \"profession, stability, innovation, efficiency and integrity\", put the quality of products first, continuously improve our marketing network, and provide users with perfect pre-sales and sales. And after-sales service, one-year product warranty, life-long maintenance, with high-quality products ."
  years_exp: 6
  skills:
    - name: PHP
      years: 5
    - name: HTML5
      years: 5.5
    - name: JavaSript
      years: 3
    - name: Photoshop
      years: 4    

# Contacts
contact:
  title: Contacts
  subtitle: Hire me.
  items:
    - title: Location
      content: GongYi,Zhengzhou,Henan Province,China
      href: "#"
    - title: Phone
      content: +86 15639088016
      href: "#"
    - title: Email
      content: snowgraceful@gmail.com
      href: "#"
    - title: Web
      content: https://snowgrace.github.io/
      href: "#"

# Products
product:
  title: Products
  subtitle: Good equipment originates from higher pursuit.
  items:
    - title: Rotary evaporator
      content: "Lorem ipsum dolor amet consectetur ut consequat siad esqudiat dolor"
      href: "#"
      icon: "icon-chemistry"
      featured: false
    - title: Glass reactor
      content: "Lorem ipsum dolor amet consectetur ut consequat siad esqudiat dolor"
      href: "#"
      icon: "color-white icon-screen-tablet"
      featured: true
    - title: Circulating water vacuum pump
      content: "Lorem ipsum dolor amet consectetur ut consequat siad esqudiat dolor"
      href: "#"
      icon: "icon-badge"
      featured: false

# Work
work:
  title: Works
  subtitle: I build the real value.
  items:
  #1
    - grid_class: "col-xs-12 col-sm-6 col-md-8 margin-b-4"
      image: "img/800x400/01.jpg"
      hide_text: "Hide"
      title: "Art Of Coding"
      subtitle: "Clean &amp; Minimalistic Design"
      description: "<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
      "
      cta: "Show me more"
      href: "#"
      tools:
        - text: "HTML5/CSS3"
        - text: "Photoshop"
        - text: "JavaSript"

  #2
    - grid_class: "col-xs-12 col-sm-6 col-md-4 margin-b-4"
      image: "img/397x400/01.jpg"
      hide_text: "Hide"
      title: "Art Of Coding"
      subtitle: "Clean &amp; Minimalistic Design"
      description: "<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
      "
      cta: "Show me more"
      href: "#"
      tools:
        - text: "HTML5/CSS3"
        - text: "Photoshop"
        - text: "JavaSript"

  #3
    - grid_class: "col-xs-12 col-sm-6 col-md-4 md-margin-b-4"
      image: "img/397x300/01.jpg"
      hide_text: "Hide"
      title: "Art Of Coding"
      subtitle: "Clean &amp; Minimalistic Design"
      description: "<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
      "
      cta: "Show me more"
      href: "#"
      tools:
        - text: "HTML5/CSS3"
        - text: "Photoshop"
        - text: "JavaSript"


  #4
    - grid_class: "col-xs-12 col-sm-6 col-md-4 md-margin-b-4"
      image: "img/397x300/02.jpg"
      hide_text: "Hide"
      title: "Art Of Coding"
      subtitle: "Clean &amp; Minimalistic Design"
      description: "<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
      "
      cta: "Show me more"
      href: "#"
      tools:
        - text: "HTML5/CSS3"
        - text: "Photoshop"
        - text: "JavaSript"

  #5
    - grid_class: "col-xs-12 col-sm-6 col-md-4"
      image: "img/397x300/03.jpg"
      hide_text: "Hide"
      title: "Art Of Coding"
      subtitle: "Clean &amp; Minimalistic Design"
      description: "<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
      "
      cta: "Show me more"
      href: "#"
      tools:
        - text: "HTML5/CSS3"
        - text: "Photoshop"
        - text: "JavaSript"
